# Generated by Django 5.1.7 on 2025-03-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="full_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="map_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="route",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
