# Generated by Django 5.1.7 on 2025-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_route_full_description_route_map_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="image",
            new_name="photo",
        ),
        migrations.RemoveField(
            model_name="route",
            name="description",
        ),
        migrations.RemoveField(
            model_name="route",
            name="full_description",
        ),
        migrations.AddField(
            model_name="route",
            name="gas_stations_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
